tasks:
  # Instructions from: https://grafana.com/docs/k6/latest/set-up/install-k6/#debianubuntu
  - name: Install k6
    init: |
      sudo gpg -k
      sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
      echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
      sudo apt-get update
      sudo apt-get install k6

  - name: Configure Poetry and install dependencies
    init: |
      poetry config virtualenvs.create false
      poetry install

vscode:
  extensions:
    - ms-toolsai.jupyter
    - ms-python.python
    - ms-python.debugpy
